apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::975049960102:role/eksrole
      username: eksrole
      groups:
        - system:masters
